Repository PathOfBuildingCommunity/PathOfBuilding-PoE2-v2, pull requests merged in 2025-01, with the labels that each got.

#4 Fix skill count not counting skills from ascendancies/tree
  src/Classes/SkillsTab.lua
Labels: bug: behaviour

#3 Fix Deep Cuts, Deadly Poison and ailment source damage
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_dex.txt
  src/Export/Skills/sup_str.txt
  src/Modules/CalcOffence.lua
Labels: crash

#2 Fix resistance bug and Against the Darkness displayStats
  src/Classes/ItemsTab.lua
  src/Modules/CalcSetup.lua
Labels: bug: behaviour

#1 Fix crash caused by dereference of non existing breakdown table
  src/Modules/CalcDefence.lua
Labels: Temp crash

#5 Enable bleed for spells and fix bleed multi when moving
  src/Modules/CalcOffence.lua
  src/Modules/CalcSetup.lua
Labels: bug: behaviour

#10 make binary operations take arbitrary number of values
  src/Data/Global.lua
Labels: bug: behaviour

#6 Fix undoing attribute nodes
  src/Classes/PassiveSpec.lua
Labels: bug: behaviour

#11 Fix base exposure, add cold exposure, fix lightning exposure
  src/Data/SkillStatMap.lua
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
  src/Modules/ConfigOptions.lua
Labels: bug: calculation

#7 Fix crash when allocation some nodes with weapon set passives
  src/Modules/CalcSetup.lua
Labels: crash

#13 Fix crash when allocating Explosive Impact
  src/Classes/SkillsTab.lua
Labels: crash

#9 Add support for Archmage
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: enhancement

#14 Fix some Skills not including their guaranteed source of Ignite/Bleed/Poison
  src/Data/SkillStatMap.lua
Labels: bug: calculation

#15 Partial Stormweaver support
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#18 Fix The Adorned not increasing effect of Corrupted Magic Jewels
  src/Modules/CalcSetup.lua
Labels: bug: calculation

#17 Fix crash when searching for Skill Gems
  src/Classes/SkillsTab.lua
Labels: crash

#16 Increased hover range for Skill Tree nodes
  src/Classes/PassiveTree.lua
Labels: enhancement

#19 Remove Ward displays and update Spirit color
  src/Data/Global.lua
  src/Modules/BuildDisplayStats.lua
  src/Modules/CalcSections.lua
Labels: user-interface

#20 Fix Widowhail not scaling Quiver mods
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#23 Fix Innervation not applying to other skills
  src/Data/SkillStatMap.lua
Labels: bug: behaviour

#24 Fix Against the Darkness applying to Attribute nodes
  src/Modules/CalcSetup.lua
Labels: bug: behaviour

#22 Fix damage scaling with Mace Strike, Bow Shot, Concoction, and other skills
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
Labels: bug: behaviour

#26 Add support for Concoction skills
  src/Data/SkillStatMap.lua
  src/Data/Skills/other.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Export/Skills/other.txt
  src/Export/Skills/sup_int.txt
  src/Export/Skills/sup_str.txt
Labels: enhancement

#21 Add support + Elemental Spell levels
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: calculation

#27 Add support for importing builds from PoE2DB
  src/Modules/BuildSiteTools.lua
Labels: enhancement

#25 Fix node power visuals while processing/calculating
  src/Classes/PassiveTreeView.lua
Labels: bug, user-interface

#29 Fix Weapon Set passives on Tree not applying correctly
  src/Modules/CalcSetup.lua
Labels: bug: behaviour

#31 Fix some increased critical damage modifiers incorrectly applying as base critical damage modifiers
  src/Data/SkillStatMap.lua
Labels: bug: calculation

#32 Fix cash when viewing breakdown of nodes in starting Witch area
  src/Classes/CalcBreakdownControl.lua
  src/Classes/PassiveSpec.lua
Labels: crash

#34 Support Renly's Training Ascendancy node
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#36 Change config option to use 1 Enemy Distance value
  src/Classes/ModStore.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: user-interface

#35 Add Support for Blood Magic Keystone
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#38 Fix weapon tree hotkey overriding other tree hotkeys
  src/Classes/PassiveTreeView.lua
Labels: bug, user-interface

#40 Fix Widowhail & other Quiver bonus scaling
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: bug: calculation

#44 Fix export of uniques
  src/Data/Uniques/ring.lua
  src/Export/Uniques/helmet.lua
Labels: bug: calculation

#42 Fix Seismic Cry being treated as an Attack instead of a hit
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug: behaviour

#43 Clicking on the skill passives display cycles through Weapon passive allocation modes
  src/Modules/Build.lua
Labels: enhancement

#45 Add support for importing builds from poe2.ninja
  src/Modules/BuildSiteTools.lua
Labels: enhancement

#46 Fix parsing for Grand Spectrum
  src/Modules/ModParser.lua
Labels: bug: behaviour

#50 Fix Arrow Speed not applying to Feathered Fletchingnode
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#49 Fix Explosion damage for Frozen Locus and Shattering Palm
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/sup_int.lua
  src/Export/Scripts/skills.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/sup_int.txt
  src/Modules/CalcActiveSkill.lua
Labels: bug: calculation

#48 Add support for Small/Notable Passive mods on all Time-Lost Jewels
  src/Modules/CalcSetup.lua
Labels: enhancement

#47 Add support for breach ring quality
  src/Classes/ItemsTab.lua
  src/Modules/ModParser.lua
Labels: enhancement

#51 Fix calculation of Base Evasion from levels
  src/Modules/CalcSetup.lua
Labels: bug: calculation

#54 Add support for 8s Recoup and new mods
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#53 Add support for all damage conversion (like Avatar of Fire)
  src/Modules/CalcOffence.lua
Labels: enhancement

#56 Add support for parsing Damage gain as (without as extra)
  src/Modules/CalcOffence.lua
Labels: enhancement

#57 Add support for Armour applying to Elemental Damage Taken
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#55 Fix radius nodes getting incorrect Time-Lost Jewel mods
  src/Modules/CalcSetup.lua
Labels: technical

#60 Add support for Offering Skills
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: enhancement

#58 Add support for Minions inheriting player Dexterity
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#63 Fix Comparison Tooltip adding Time Lost Jewel mods to incorrect radiusNodes
  src/Classes/ItemsTab.lua
  src/Classes/TreeTab.lua
  src/Modules/CalcSetup.lua
Labels: technical, bug: behaviour
